// This file is autogenerated by VESC Tool

#include "libBuffer.h"
#include "conf_default.h"
#include "confparser.h"

int32_t confparser_serialize_main_config_t(uint8_t *buffer, const main_config_t *conf) {
	int32_t ind = 0;

	libBufferAppend_uint32(buffer, MAIN_CONFIG_T_SIGNATURE, &ind);

	buffer[ind++] = (uint8_t)conf->controller_id;
	buffer[ind++] = conf->can_baud_rate;
	libBufferAppend_int16(buffer, conf->cell_num, &ind);
	libBufferAppend_int16(buffer, conf->temp_num, &ind);
	libBufferAppend_float32_auto(buffer, conf->balance_start_voltage, &ind);
	libBufferAppend_float32_auto(buffer, conf->balance_difference_threshold, &ind);
	libBufferAppend_float32_auto(buffer, conf->soft_overvoltage, &ind);
	libBufferAppend_float32_auto(buffer, conf->soft_undervoltage, &ind);
	libBufferAppend_float32_auto(buffer, conf->hard_overvoltage, &ind);
	libBufferAppend_float32_auto(buffer, conf->hard_undervoltage, &ind);
	libBufferAppend_float16(buffer, conf->t_charge_max, 10, &ind);
	libBufferAppend_float16(buffer, conf->t_discharge_max, 10, &ind);
	libBufferAppend_float32_auto(buffer, conf->not_used_current_threshold, &ind);
	libBufferAppend_int32(buffer, conf->not_used_timeout, &ind);

	return ind;
}

bool confparser_deserialize_main_config_t(const uint8_t *buffer, main_config_t *conf) {
	int32_t ind = 0;

	uint32_t signature = libBufferGet_uint32(buffer, &ind);
	if (signature != MAIN_CONFIG_T_SIGNATURE) {
		return false;
	}

	conf->controller_id = buffer[ind++];
	conf->can_baud_rate = buffer[ind++];
	conf->cell_num = libBufferGet_int16(buffer, &ind);
	conf->temp_num = libBufferGet_int16(buffer, &ind);
	conf->balance_start_voltage = libBufferGet_float32_auto(buffer, &ind);
	conf->balance_difference_threshold = libBufferGet_float32_auto(buffer, &ind);
	conf->soft_overvoltage = libBufferGet_float32_auto(buffer, &ind);
	conf->soft_undervoltage = libBufferGet_float32_auto(buffer, &ind);
	conf->hard_overvoltage = libBufferGet_float32_auto(buffer, &ind);
	conf->hard_undervoltage = libBufferGet_float32_auto(buffer, &ind);
	conf->t_charge_max = libBufferGet_float16(buffer, 10, &ind);
	conf->t_discharge_max = libBufferGet_float16(buffer, 10, &ind);
	conf->not_used_current_threshold = libBufferGet_float32_auto(buffer, &ind);
	conf->not_used_timeout = libBufferGet_int32(buffer, &ind);

	return true;
}

void confparser_set_defaults_main_config_t(main_config_t *conf) {
	conf->controller_id = CONF_CONTROLLER_ID;
	conf->can_baud_rate = CONF_CAN_BAUD_RATE;
	conf->cell_num = CONF_CELL_NUM;
	conf->temp_num = CONF_TEMP_NUM;
	conf->balance_start_voltage = CONF_BALANCE_START;
	conf->balance_difference_threshold = CONF_BALANCE_DIFF;
	conf->soft_overvoltage = CONF_SOFT_OVER;
	conf->soft_undervoltage = CONF_SOFT_UNDER;
	conf->hard_overvoltage = CONF_HARD_OVER;
	conf->hard_undervoltage = CONF_HARD_UNDER;
	conf->t_charge_max = CONF_T_CHARGE_MAX;
	conf->t_discharge_max = CONF_T_DISCHARGE_MAX;
	conf->not_used_current_threshold = CONF_NOT_USED_THRESHOLD;
	conf->not_used_timeout = CONF_NOT_USED_TIMEOUT;
}

