// This file is autogenerated by VESC Tool

#ifndef CONFXML_H_
#define CONFXML_H_

#include "mainDataTypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_MAIN_CONFIG_T__SIZE		2031

// Variables
const extern uint8_t data_main_config_t_[];

// CONFXML_H_
#endif
